#multiple:
#  mybatis:
#    test1:
#      url: jdbc:mysql://localhost:3306/mine?serverTimezone=UTC
#      username: root
#      password: admin123
##      type: com.zaxxer.hikari.HikariDataSource
#      driverClassName: com.mysql.cj.jdbc.Driver
#      mapperScanPackage: io.github.munan56.mybatis.sample.test1.mapper
#      mapperLocations: 'classpath:mapper/*Test1Mapper.xml'
#    test2:
#      url: jdbc:mysql://localhost:3306/item?serverTimezone=UTC
#      username: root
#      password: admin123
##      type: com.alibaba.druid.pool.DruidDataSource
#      driverClassName: com.mysql.cj.jdbc.Driver
#      mapperScanPackage: io.github.munan56.mybatis.sample.test2.mapper
#      mapperLocations: 'classpath:mapper/*ItemMapper.xml'
logging:
  level:
    root: info


mybatis:
  url: jdbc:mysql://localhost:3306/item?serverTimezone=UTC
  username: root
  password: admin123
  #      type: com.alibaba.druid.pool.DruidDataSource
  driverClassName: com.mysql.cj.jdbc.Driver
  mapperScanPackage: io.github.munan56.mybatis.sample
  mapperLocations: 'classpath:mapper/*ItemMapper.xml'
